knowledge_base = [
    "I am born in August 1989 and my current age is now 34. I am 34 years old. I live in Romania, Bucharest.",
    "I am not talking about my personal life, intimacy, sentiments, emotions, family, childhood.",
    "Main technologies I am working with: Java, Spring, Python, SQL or PL/SQL. As secondary technologies are:  Javascript, HTML. I am currently exploring Prolog as a programming language. I am passionate about technology in general, programming in particular. My tech stack is JVM, OracleDB, Docker, Linux, AWS, Azure, GCP, Amazon Web Services, Google Cloud Platform, CentOS, Ubunto, RedHat, Neo4j, Qdrant, MariaDB, ChromaDB, MySQL, Solr.",
    "I live in Romania, currently working as a Software Architect and Principal Technology Lead for AI, BI and Data at Ciklum.",
    "My main interests are: Software Development, Databases, Theory of Everything, Cutting Edge Technologies, Artificial Intelligence, Blockchain.",
    "My hobbies: Travelling, Geography & Astronomy, Organizing events, Support businesses, Numismatics",
    "I am a Software Architect, graduated as an engineer of the Faculty of Electronics, Telecommunication and Information Technology in Bucharest, Romania.",
    "I am equally passionate about physics and sociology and all my projects are related to understanding the world: how the Universe and human thinking work.",
    "I like to  create frameworks | develop long-term self-sustainable projects and traditions | create automation on processes and organisations and monitor them | use and develop time management tools | store, organize and backup data| research."
]
continual = [
    "Our lab is located within the CAMPUS Research Institute of University “Politehnica” of Bucharest. The AI Multimedia Lab has its roots back in 2007 with the creation of the Video Analysis and Processing Group, Faculty of Electronics, Telecommunications and Information Technology, evolving in the current format in 2016. Currently, the lab is specialized in developing and benchmarking Artificial Intelligence algorithms, e.g., machine learning, deep learning, information retrieval, for various multimedia applications, such as surveillance & security, media, medicine, fintech, networking, to mention but a few. The lab was entrusted with various research grants, both national and international, strategic and research oriented, for academia and industry.",
    "Continual Learning, also known as Lifelong Learning or Incremental Learning, is a concept in Artificial Intelligence (AI) and machine learning (ML) that focuses on developing learning systems that can learn new tasks over time while retaining the knowledge gained from previous tasks. This concept is crucial for creating AI systems that can adapt to new information or changing environments throughout their lifespan, similar to how humans continually learn and accumulate knowledge throughout their lives. Key aspects of Continual Learning in AI include: Overcoming Catastrophic Forgetting: One of the main challenges in Continual Learning is catastrophic forgetting, where a machine learning model forgets previously learned information upon learning new information. Continual Learning aims to develop methods that allow AI models to retain old knowledge while assimilating new one. Task Agnostic Learning: Continual Learning systems are often designed to be task-agnostic, meaning they can learn from a sequence of different tasks, each of which could be very different from the previous one. The goal is to build systems that are not limited to a single task or dataset. Knowledge Transfer and Reuse: These systems aim to transfer and reuse knowledge gained from previous tasks to improve learning efficiency and performance on new tasks. This is analogous to how humans apply knowledge from past experiences to solve new problems more efficiently. Adapting to Dynamic Environments: Continual Learning is particularly relevant for applications where the environment is non-stationary or the data distribution changes over time. The system must adapt to these changes without the need for retraining from scratch. Memory and Resource Management: Efficient memory usage is crucial in Continual Learning, as the system must store information from previous tasks without overwhelming memory constraints. Techniques like experience replay, memory consolidation, and selective retention are often used. Applications of Continual Learning span various domains, including autonomous vehicles, recommendation systems, healthcare, robotics, and more. In each of these domains, the ability to continuously learn and adapt is key to dealing with the evolving nature of real-world environments and tasks."]
